volumes:
    maildir: {}

services:
    mail:
        image: mailhog/mailhog
        container_name: mailhog
        ports:
            - 1025:1025
            - 8025:8025
        environment:
            MH_STORAGE: maildir
            MH_MAILDIR_PATH: /tmp
        volumes:
            - maildir:/tmp
        networks:
            - wpnetwork

networks:
    wpnetwork:
        name: %NETWORK_NAME%_default
        external: true
