name: Deploy Plugin to WordPress Directory

on:
  pull_request:
    branches:
      - master

jobs:
#  test:
#    strategy:
#      matrix:
#        php: [ '7.2', '8.0', '8.2' ] # PHP versions to check.
#        wp: [ 'latest', '5.9' ]      # WordPress version to check.
#    uses: tarosky/workflows/.github/workflows/wp-unit-test.yml@main
#    with:
#      php_version: ${{ matrix.php }}
#      wp_version: ${{ matrix.wp }}

  phpcs:
    uses: tarosky/workflows/.github/workflows/phpcs.yml@main
    with:
      version: 8.0

  phplint:
    uses: tarosky/workflows/.github/workflows/phplint.yml@main

  assets:
    uses: tarosky/workflows/.github/workflows/npm.yml@main
    with:
      node_version: 16
      package: package

  status-check:
    name: Status Check
    if: always()
    runs-on: ubuntu-latest
    needs: [ phpcs, phplint, assets ] # [ test, phpcs, phplint, assets ]
    steps:
    - uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}

